import type { Celebrity } from './types';

/**
 * THE CELEBRITY GRAVEYARD ROSTER.
 *
 * ⚠️ EVERY ENTRY HERE IS FICTIONAL PARODY CONTENT. ⚠️
 *
 * These are jokes about public personas, in the same spirit as a cartoon
 * in a newspaper. Rules followed by every entry below:
 *
 *  - Nobody here is described as dead. "Graves" are a running joke about
 *    the site itself, and the status lines say so.
 *  - No real event, real quote or real allegation appears anywhere.
 *  - Nothing claims any person bought, owns, holds, endorses or is
 *    affiliated with $RIP or Digital Grave.
 *  - "Last words" are invented catchphrase-style jokes and are always
 *    labelled as fictional in the interface.
 *
 * This file is the single source of content. When the database arrives in
 * a later phase, the admin panel will edit these same fields — the shape
 * will not change, so no page will need rewriting.
 */
export const CELEBRITIES: Celebrity[] = [
  {
    id: 'cel-001',
    slug: 'elon-musk',
    name: 'ELON MUSK',
    displayName: 'ELON MUSK',
    category: 'BUSINESS',
    title: '🚀 THE DOGE IMMORTAL',
    status: '💀 SOMEHOW STILL ALIVE',
    graveStatus: 'ALIVE',
    causeOfDeath: 'POSTED ONE MORE TWEET',
    lastWords: 'To the moon.',
    achievement: '🚀 DOGE IMMORTAL',
    graveNumber: 1,
    description: [
      'Born to tweet.',
      'Raised by rockets.',
      'Eventually discovered that the cemetery has Wi-Fi.',
      'Currently trying to launch the graveyard into orbit.',
    ],
    avatar: {
      hair: 'swoop',
      hairColor: '#3b2f2a',
      skin: '#e8b894',
      accessory: 'none',
      accent: 'legendary',
      emblem: '🚀',
    },
    stats: {
      immortality: 97,
      resurrections: 4,
      longestLife: 'One more post',
      comedy: 92,
      legend: 95,
    },
    featured: true,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['elon', 'musk', 'doge', 'rocket', 'tesla'],
  },
  {
    id: 'cel-002',
    slug: 'donald-trump',
    name: 'DONALD TRUMP',
    displayName: 'DONALD TRUMP',
    category: 'POLITICS',
    title: '👑 THE GRAVE PRESIDENT',
    status: '💀 STILL NEGOTIATING WITH DEATH',
    graveStatus: 'ALIVE',
    causeOfDeath: 'MADE ANOTHER DEAL',
    lastWords: 'Nobody does graves better than me.',
    achievement: '👑 GRAVE PRESIDENT',
    graveNumber: 2,
    description: [
      'Arrived at the cemetery and immediately asked to speak to the owner.',
      'Renegotiated the terms of the afterlife.',
      'The gravestone is now, reportedly, very large.',
    ],
    avatar: {
      hair: 'sweep',
      hairColor: '#e6c45c',
      skin: '#f0b98a',
      accessory: 'tie',
      accent: 'legendary',
      emblem: '👑',
    },
    stats: {
      immortality: 90,
      resurrections: 3,
      longestLife: 'Four more years',
      comedy: 88,
      legend: 89,
    },
    featured: true,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['donald', 'trump', 'president', 'deal'],
  },
  {
    id: 'cel-003',
    slug: 'cz',
    name: 'CHANGPENG ZHAO',
    displayName: 'CZ',
    category: 'CRYPTO',
    title: '🛡️ SAFU SURVIVOR',
    status: '🟢 STILL ALIVE',
    graveStatus: 'ALIVE',
    causeOfDeath: 'TOO MUCH BUIDLING',
    lastWords: 'Funds are safu.',
    achievement: '🛡️ SAFU SURVIVOR',
    graveNumber: 3,
    description: [
      'Showed up at the graveyard and immediately audited it.',
      'Declared the cemetery solvent.',
      'The gravestones are, apparently, safu.',
    ],
    avatar: {
      hair: 'crop',
      hairColor: '#1a1a1f',
      skin: '#e8bd96',
      accessory: 'none',
      accent: 'alive',
      emblem: '🛡️',
    },
    stats: {
      immortality: 84,
      resurrections: 2,
      longestLife: 'Four years of BUIDL',
      comedy: 76,
      legend: 85,
    },
    featured: true,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['cz', 'changpeng', 'zhao', 'safu', 'binance', 'buidl'],
  },
  {
    id: 'cel-004',
    slug: 'satoshi-nakamoto',
    name: 'SATOSHI NAKAMOTO',
    displayName: 'SATOSHI NAKAMOTO',
    category: 'LEGENDS',
    title: '👻 THE UNDEAD FOUNDER',
    status: '👻 NEVER FOUND',
    graveStatus: 'UNDEAD',
    causeOfDeath: 'DISAPPEARED BEFORE THE GRAVE COULD FIND HIM',
    lastWords: '...',
    achievement: '👻 UNKNOWN IMMORTAL',
    graveNumber: 4,
    description: [
      'The gravedigger dug a hole.',
      'The hole was already empty.',
      'Nobody has seen the tombstone, but everyone agrees it exists.',
      'Possibly a ghost. Possibly a group of ghosts.',
    ],
    avatar: {
      hair: 'hood',
      hairColor: '#2a2a33',
      skin: '#1c1c22',
      accessory: 'question',
      accent: 'ghost',
      emblem: '👻',
    },
    stats: {
      immortality: 100,
      resurrections: 0,
      longestLife: 'Since the genesis block',
      comedy: 84,
      legend: 100,
    },
    featured: true,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['satoshi', 'nakamoto', 'bitcoin', 'founder', 'anon'],
  },
  {
    id: 'cel-005',
    slug: 'vitalik-buterin',
    name: 'VITALIK BUTERIN',
    displayName: 'VITALIK BUTERIN',
    category: 'CRYPTO',
    title: '🧠 THE ETERNAL BUILDER',
    status: '🟣 TOO BUSY TO DIE',
    graveStatus: 'IMMORTAL',
    causeOfDeath: 'WROTE ANOTHER WHITEPAPER',
    lastWords: "Let's improve the protocol.",
    achievement: '🧠 PROTOCOL IMMORTAL',
    graveNumber: 5,
    description: [
      'Read the cemetery documentation. Found three inefficiencies.',
      'Proposed an upgrade to the concept of dying.',
      'The graveyard is now on a roadmap.',
    ],
    avatar: {
      hair: 'bowl',
      hairColor: '#c9986a',
      skin: '#f0d3bb',
      accessory: 'none',
      accent: 'reborn',
      emblem: '🧠',
    },
    stats: {
      immortality: 96,
      resurrections: 5,
      longestLife: 'Several hard forks',
      comedy: 81,
      legend: 94,
    },
    featured: false,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['vitalik', 'buterin', 'ethereum', 'protocol', 'whitepaper'],
  },
  {
    id: 'cel-006',
    slug: 'michael-saylor',
    name: 'MICHAEL SAYLOR',
    displayName: 'MICHAEL SAYLOR',
    category: 'BUSINESS',
    title: '₿ THE NEVER SELLER',
    status: '🟢 IMMORTAL',
    graveStatus: 'IMMORTAL',
    causeOfDeath: 'STILL BUYING BITCOIN',
    lastWords: 'Bitcoin.',
    achievement: '₿ DIAMOND IMMORTAL',
    graveNumber: 6,
    description: [
      'Refused the grave. Bought the cemetery instead.',
      'Then bought the dip on the cemetery.',
      'Has never once pressed the sell button. Not even by accident.',
    ],
    avatar: {
      hair: 'slick',
      hairColor: '#5a5a66',
      skin: '#e9c3a2',
      accessory: 'tie',
      accent: 'legendary',
      emblem: '₿',
    },
    stats: {
      immortality: 99,
      resurrections: 0,
      longestLife: 'Never sold, never died',
      comedy: 79,
      legend: 92,
    },
    featured: false,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['michael', 'saylor', 'bitcoin', 'btc', 'hodl', 'diamond'],
  },
  {
    id: 'cel-007',
    slug: 'sam-bankman-fried',
    name: 'SAM BANKMAN-FRIED',
    displayName: 'SAM BANKMAN-FRIED',
    category: 'CRYPTO',
    title: '🪦 THE PERMA-DEAD',
    status: '💀 GRAVE LOCKED',
    graveStatus: 'DEAD',
    causeOfDeath: 'TOO MUCH LEVERAGE',
    lastWords: 'It was slightly more than 1x.',
    achievement: '🪦 PERMA-DEAD',
    graveNumber: 7,
    description: [
      'Entered the cemetery with a very confident spreadsheet.',
      'The spreadsheet had one extra zero in it.',
      'The gravestone does not have a withdraw button.',
    ],
    avatar: {
      hair: 'curls',
      hairColor: '#4a3b30',
      skin: '#eec5a4',
      accessory: 'none',
      accent: 'dead',
      emblem: '🪦',
    },
    stats: {
      immortality: 12,
      resurrections: 0,
      longestLife: 'One leverage cycle',
      comedy: 95,
      legend: 70,
    },
    featured: false,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['sam', 'bankman', 'fried', 'sbf', 'leverage'],
  },
  {
    id: 'cel-008',
    slug: 'do-kwon',
    name: 'DO KWON',
    displayName: 'DO KWON',
    category: 'CRYPTO',
    title: '🪦 ALGORITHM SURVIVOR',
    status: '💀 GRAVE FOUND',
    graveStatus: 'DEAD',
    causeOfDeath: 'ALGORITHM FAILED TO RESURRECT',
    lastWords: 'The peg will hold.',
    achievement: '🪦 FAILED RESURRECTION',
    graveNumber: 8,
    description: [
      'Wrote an algorithm guaranteed to prevent death.',
      'The algorithm was very confident.',
      'The algorithm is now also in the cemetery.',
    ],
    avatar: {
      hair: 'flat',
      hairColor: '#16161b',
      skin: '#edc7a6',
      accessory: 'none',
      accent: 'dead',
      emblem: '🪦',
    },
    stats: {
      immortality: 8,
      resurrections: 1,
      longestLife: 'Until the peg broke',
      comedy: 90,
      legend: 68,
    },
    featured: false,
    parodyOnly: true,
    createdAt: '2026-09-11',
    searchTerms: ['do', 'kwon', 'algorithm', 'peg', 'terra', 'luna'],
  },
];

/** The exact disclaimer required on every celebrity surface. */
export const PARODY_DISCLAIMER =
  'Celebrity profiles on Digital Grave are fictional parody content created for entertainment purposes only. They are not affiliated with, endorsed by, or representative of the people shown.';
